version: "2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: <nome_do_bot>
    command: python -u ./scheduller.py
    restart: unless-stopped
    networks:
      connect:
    volumes:
      - /var/docker_volumes/<nome_do_bot>/logs :/app/logs
    environment:
      PYTHONUNBUFFERED: 1
      MODE: PRD
    pull_policy: build 

networks:
  connect:
    external: true
